blog/urls.py
from django.urls import path, reverse_lazy
from .views import BlogListView, BlogDetailView


app_name = 'blog'

urlpatterns = [
    path('',BlogListView.as_view(),name='all'),
    path('<slug:slug>',BlogDetailView.as_view(),name='detail')
]

home/urls.py
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView
from .views import homePageView, aboutPageView, resumePageView
from . import views


app_name = 'home'

urlpatterns = [
    path('',homePageView,name='home_base'),
    path('home/',homePageView,name='home_page'),
    path('about/',aboutPageView,name='about'),
    path('resume/',resumePageView,name='resume'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('blog/',include('blog.urls')),
    path('notes/',include('notes.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    ]


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

notes/urls.py
from django.urls import path, reverse_lazy
from .views import NoteDetailView, NoteListView


app_name = 'notes'

urlpatterns = [
    path('',NoteListView.as_view(),name='all'),
    path('<slug:slug>',NoteDetailView.as_view(),name='detail')
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from mdeditor.fields import MDTextField #https://developpaper.com/implementation-of-beautiful-django-markdown-rich-text-app-plug-in/
from django.core.validators import FileExtensionValidator
import datetime
import string
import random

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

# Create your models here.
    
#https://www.kodnito.com/posts/slugify-urls-django/


class BlogPost(models.Model):
    PUBLISHED = 'PUB'
    DRAFT = 'DRA'
    PUBLISH_CHOICES = (
        (PUBLISHED,'Publish'),
        (DRAFT,'Save as Draft')
    )
    title = models.CharField(max_length=255)
    intro = models.TextField(blank=True,null=True)
    content = MDTextField()
    image = models.ImageField(upload_to='files',blank=True,null=True)
    powerpoint = models.TextField(null=True,blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    created_time = models.DateTimeField(auto_created=True)
    published = models.CharField(
                max_length=3,
                choices=PUBLISH_CHOICES,
                default=DRAFT)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        try:
            self.slug = slugify(self.title)
            super(BlogPost, self).save(*args, **kwargs)
        except:
            if not self.slug:
                self.slug = slugify(self.title + "-" + rand_slug())
            super(BlogPost, self).save(*args, **kwargs)

    objects = models.Manager()

    class Meta:
        ordering = ('created_time',)



class Persona(models.Model):
    name = models.CharField(max_length=40)
    title = models.CharField(max_length=40, null=True,blank=True)
    image = models.ImageField(upload_to='files',blank=True,null=True)
    content = MDTextField()
    blog = models.ForeignKey(BlogPost, on_delete=models.SET_NULL, null=True, blank=True)
    objects = models.Manager()

home/models.py
from django.db import models
from mdeditor.fields import MDTextField #https://developpaper.com/implementation-of-beautiful-django-markdown-rich-text-app-plug-in/
from django.core.validators import FileExtensionValidator


# Create your models here.

class HomePage(models.Model):
    content = MDTextField()
    objects = models.Manager()

class AboutPage(models.Model):
    content = MDTextField()
    objects = models.Manager()

class Resume(models.Model):
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='files',validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    objects = models.Manager()

notes/models.py
from django.db import models
from django.utils.text import slugify
from mdeditor.fields import MDTextField #https://developpaper.com/implementation-of-beautiful-django-markdown-rich-text-app-plug-in/
from django.core.validators import FileExtensionValidator
import datetime
import string
import random

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

# Create your models here.
    
#https://www.kodnito.com/posts/slugify-urls-django/


class Note(models.Model):
    title = models.CharField(max_length=255)
    content = MDTextField()
    slug = models.SlugField(max_length=255, unique=True)
    created_time = models.DateTimeField(auto_created=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        try:
            self.slug = slugify(self.title)
            super(Note, self).save(*args, **kwargs)
        except:
            if not self.slug:
                self.slug = slugify(self.title + "-" + rand_slug())
            super(Note, self).save(*args, **kwargs)

    objects = models.Manager()

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import BlogPost, Persona
# Create your views here.

class BlogListView(generic.ListView):
    model = BlogPost
    ordering = ['-created_time']

class BlogDetailView(generic.DetailView):
    model = BlogPost

class PersonaListView(generic.ListView):
    model = Persona
    
class PersonaDetailView(generic.DetailView):
    model = Persona

home/views.py
from django.shortcuts import render
from django.views import View, generic
from .models import HomePage, AboutPage, Resume

def homePageView(request):
    homepage = HomePage.objects.all().reverse()[0]
    context = {'homepage': homepage}
    return render(request, 'pages/home.html', context)

def aboutPageView(request):
    aboutpage = AboutPage.objects.all().reverse()[0]
    context = {'aboutpage': aboutpage}
    return render(request, 'pages/about.html', context)

def resumePageView(request):
    resume = Resume.objects.all().reverse()[0]
    context = {'resume': resume}
    return render(request, 'pages/resume.html', context)

def handler404(request, exception):
    return render(request, 'pages/404.html', status=404)

def handler500(request):
    return render(request, 'pages/500.html', status=500)

notes/views.py
from django.shortcuts import render
from django.views import generic
from .models import Note

# Create your views here.

class NoteListView(generic.ListView):
    model = Note

class NoteDetailView(generic.DetailView):
    model = Note

blog/templates/blog/blog_content.html
{% load markdown_extras %}

<div class="jumbotron">
    <div align="center">
        <div class="card border-primary mb-3" align="center" style="max-width: 95%">
            <div class="card-header">
                <h1 class="card-title">
                    <a href="{% url 'blog:detail' blogpost.slug %}">
                        {{ blogpost.title }}
                    </a>
                </h1>
            </div>
            <div class="card-body">
            
                <h4 class="card-title">
                    {{ blogpost.created_time.date }}
                </h4>
                
                {% if blogpost.intro %}
                    <p>{{ blogpost.intro }}</p>                
                {% endif %}

                {% if blogpost.powerpoint %}
                    {{ blogpost.powerpoint | safe }}
                    </br>
                {% endif %}

                {% if blogpost.persona_set.count %}
                    <br/>
                    <h3>Product User Personas</h3>
                    <br/>
                    {% include 'blog/components/blog_personas.html'%}
                {% endif %}
                
                {{ blogpost.content | markdown | safe  }}
            </div>
        </div>
    </div>  
</div>

blog/templates/blog/blog_footer.html
<div class="col-lg-8 col-md-10 mx-auto" align="center">
  <div class="btn-group">
    {% if blogpost.get_previous_by_created_time.published == 'PUB' %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="{{ blogpost.get_previous_by_created_time.title }}"
      onclick="location.href='{% url 'blog:detail' blogpost.get_previous_by_created_time.slug %}'"
    >
      See Previous Post
    </button>
    {% endif %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="Go to Blog Home"
      onclick="location.href='{% url 'blog:all' %}'"
    >
      All Blog Posts
    </button>
    {% if blogpost.get_next_by_created_time.published == 'PUB' %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="{{ blogpost.get_next_by_created_time.title }}"
      onclick="location.href='{% url 'blog:detail' blogpost.get_next_by_created_time.slug %}'"
    >
      See Next Post
    </button>
    {% endif %}
  </div>
</div>

blog/templates/blog/blog_listall.html
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="display-4" align="center">Blog Posts</h1>
    {% if user.is_superuser %}
      <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="Write New Blog"
      onclick="location.href='{% url 'admin:blog_blogpost_add' %}'"
    >
      Write New Blog
    </button>
    {% endif %}
    </br>
    </br>
    {% if blogpost_list %}
      {% for blogpost in blogpost_list %}
        {% if user.is_superuser or blogpost.published == 'PUB'  %}
          {% include 'blog/components/blog_listcard.html' %}
        {% endif %}
      {% endfor %}
    {% else %}
    <div/>
    {% endif %}
  </div>
</div>

blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}


{% block meta %}
    {% if user.is_superuser or blogpost.published == 'PUB' %}
        <meta name="twitter:title" content="{{blogpost.title}}">
        <meta property="og:title" content="{{blogpost.title}}">
        {% if blogpost.intro %}
            <meta name="twitter:description" content="{{blogpost.intro}}">
            <meta property="og:description" content="{{blogpost.intro}}">
        {% else %}
            <meta name="twitter:description" content="{{blogpost.title}}">
            <meta property="og:description" content="{{blogpost.title}}">
        {% endif %}
    {% else %}
        <meta http-equiv="REFRESH" content="1;url={% url 'blog:all' %}">
    {% endif %}
{% endblock%}

{% block title %}
    {% if user.is_superuser or blogpost.published == 'PUB' %}
        {{blogpost.title}}
    {% endif %}
{% endblock %}

{% block content %}
    {% if user.is_superuser or blogpost.published == 'PUB' %}
        {% include 'blog/blog_content.html' %}
        {% include 'blog/blog_footer.html' %}
    {% else %}
    <div style="text-align: center">
        </br>
        <h1>THIS PAGE DOES NOT EXIST.</h1>
        </br>
        <h1>REDIRECTING TO BLOGS.</h1>
        </br>
    </div>
    {% endif %}
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'base.html' %}


{% block meta %}
<meta name="twitter:title" content="Blogs - JohnShearin.com">
<meta name="twitter:description" content="Blogs written by John Shearin">
{% endblock%}

{% block title %}
Blogs - JohnShearin.com
{% endblock %}

{% block content %}
<head>
  <title>Blog Posts</title>
</head>
{% include 'blog/blog_listall.html' %}
{% endblock %}

blog/templates/blog/components/blog_listcard.html
{% load markdown_extras %}

<div align="center">
      <div class="card border-primary mb-3" align="center" style="max-width: 80%">
        <div class="card-header">
          <h4 class="card-title">
            <a href="{% url 'blog:detail' blogpost.slug %}">
              {{ blogpost.title }}
            </a>
          </h4>
        </div>
        <div class="card-body">
          <h6 class="card-title">
            {{blogpost.created_time.date}}, {{blogpost.created_time.time}}
          </h6>
          <p class="card-text">
            {% if blogpost.intro %}
              {{ blogpost.intro | truncatewords:75 }}
            {% else %}
              {{ blogpost.content | markdown | safe | truncatewords:75 }}
            {% endif %}
          </p>
        </div>
      </div>
    </div>

blog/templates/blog/components/blog_personas.html
{% load markdown_extras %}

{% for persona in blogpost.persona_set.all %}
<div class="card mb-3" style="width: 40%">
    <h3 class="card-header text-white bg-info">{{ persona.name }}</h3>
    {% if persona.title %}
        <div class="card-body">
            <h5 class="card-title">{{ persona.title }}</h5>
        </div>
    {% endif %}
    {% if persona.image %}
        <div class="card-body">
            <img src="{{ persona.image }}" alt="{{ persona.title }}"/> 
        </div>
    {% endif %}
    <div class="card-body">
        {{ persona.content }}
    </div>
</div>
<br/>
{% endfor %}

home/templates/pages/about.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block meta %}
    <meta name="twitter:title" content="About John - JohnShearin.com">
    <meta name="twitter:description" content="Learn about John Shearin">
{% endblock%}

{% block content %}
<div class="jumbotron">
    <div class="container" align="center">
        {{ aboutpage.content | markdown | safe}}
    </div>
    {% include 'partials/footer.html' %}
</div>
{% endblock %}

home/templates/pages/home.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% block content %}
{% include '../partials/home_header.html'%}

<div class="jumbotron">
    <div class="container" align="center">
        {{ homepage.content | markdown | safe }}
    </div>
</div>
{% include 'partials/footer.html' %}
{% endblock %}

home/templates/pages/resume.html
{% extends 'base.html' %}
{% block content %}

{% block meta %}
    <meta name="twitter:title" content="Resume">
    <meta name="twitter:description" content="View John's Resume">
{% endblock%}

<div class="jumbotron">
    <div class="container" align="center">
        <embed src="{{ resume.file.url }}" type="application/pdf" height="1050px" width="750">
    </div>
    <div class="container" align="center">
    {% include 'partials/footer.html' %}
    </div>
</div>

{% endblock %}

home/templates/partials/home_header.html
{% load static %}

<header class="masthead" style="background-image: url({% static 'img/cover_photo.jpg' %})">
  <div class="overlay">
  </div>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <button 
            class="display-1" 
            style="background-color: white; opacity: 0.5; padding-left:.2em"
            onclick="location.href='{% url 'home:resume' %}'"
          >
            John Shearin
          </button>
        </div>
      </div>
  </div>
</header>

notes/templates/notes/components/notes_listcard.html
{% load markdown_extras %}

<div align="center">
      <div class="card border-primary mb-3" align="center" style="max-width: 80%">
        <div class="card-header">
          <h4 class="card-title">
            <a href="{% url 'notes:detail' note.slug %}">
              {{ note.title }}
            </a>
          </h4>
        </div>
        <div class="card-body">
          <h6 class="card-title">
            {{note.created_time.date}}, {{note.created_time.time}}
          </h6>
          <p class="card-text">
              {{ note.content | markdown | safe | truncatewords:75 }}
          </p>
        </div>
      </div>
    </div>

notes/templates/notes/note_detail.html
{% extends 'base.html' %}


{% block meta %}
    {% if user.is_superuser %}
    {% else %}
        <meta http-equiv="REFRESH" content="1;url={% url 'home:home_page' %}">
    {% endif %}
{% endblock%}

{% block title %}
    {% if user.is_superuser %}
        {{note.title}}
    {% endif %}
{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        {% include 'notes/notes_content.html' %}
        {% include 'notes/notes_footer.html' %}
    {% else %}
    <div style="text-align: center">
        </br>
        <h1>THIS PAGE DOES NOT EXIST.</h1>
        </br>
        <h1>REDIRECTING TO HOME PAGE.</h1>
        </br>
    </div>
    {% endif %}
{% endblock %}

notes/templates/notes/note_list.html
{% extends 'base.html' %}

{% block title %}
Notes - JohnShearin.com
{% endblock %}


{% block meta %}
    {% if user.is_superuser %}
    {% else %}
        <meta http-equiv="REFRESH" content="1;url={% url 'home:home_page' %}">
    {% endif %}
{% endblock%}


{% block content %}
{% if user.is_superuser %}
<head>
  <title>Notes</title>
</head>
{% include 'notes/notes_listall.html' %}
{% else %}
    <div style="text-align: center">
        </br>
        <h1>THIS PAGE DOES NOT EXIST.</h1>
        </br>
        <h1>REDIRECTING TO HOME PAGE.</h1>
        </br>
    </div>
{% endif %}
{% endblock %}

notes/templates/notes/notes_content.html
{% load markdown_extras %}

<div class="jumbotron">
    <button
        type="button"
        class="btn btn-secondary"
        data-toggle="tooltip"
        data-placement="top"
        title=""
        data-original-title="Edit Note"
        onclick="location.href='{% url 'admin:notes_note_change' note.id %}'"
        >
        Edit Note
    </button>
    </br>
    </br>
    <div align="center">
        <div class="card border-primary mb-3" align="center" style="max-width: 95%">
            <div class="card-header">
                <h1 class="card-title">
                    <a href="{% url 'notes:detail' note.slug %}">
                        {{ note.title }}
                    </a>
                
                </h1>
                <h1 class="card-title">
                </h1>
            </div>
            <div class="card-body">
                <h4 class="card-title">
                    {{ note.created_time.date }}
                </h4>
                {{ note.content | markdown | safe  }}
            </div>
        </div>
    </div>  
</div>

notes/templates/notes/notes_footer.html
<div class="col-lg-8 col-md-10 mx-auto" align="center">
  <div class="btn-group">
    {% if note.get_previous_by_created_time %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="{{ note.get_previous_by_created_time.title }}"
      onclick="location.href='{% url 'notes:detail' note.get_previous_by_created_time.slug %}'"
    >
      Previous Note
    </button>
    {% endif %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="Go to Notes Home"
      onclick="location.href='{% url 'notes:all' %}'"
    >
      All Notes
    </button>
    {% if note.get_next_by_created_time %}
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="{{ note.get_next_by_created_time.title }}"
      onclick="location.href='{% url 'notes:detail' note.get_next_by_created_time.slug %}'"
    >
      Next Note
    </button>
    {% endif %}
  </div>
</div>

notes/templates/notes/notes_listall.html
<div class="jumbotron">
  <div class="container-fluid">
    <h1 class="display-4" align="center">Notes</h1>
    <button
      type="button"
      class="btn btn-secondary"
      data-toggle="tooltip"
      data-placement="top"
      title=""
      data-original-title="Add New Note"
      onclick="location.href='{% url 'admin:notes_note_add' %}'"
    >
    Add New Note
    </button>
    </br>
    </br>
    {% if note_list %}
      {% for note in note_list reversed %}
        {% if user.is_superuser %}
          {% include 'notes/components/notes_listcard.html' %}
        {% endif %}
      {% endfor %}
    {% else %}
    <div/>
    {% endif %}
  </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="twitter:card" content="summary">

    {% block meta %}
        <meta name="twitter:title" content="JohnShearin.com">
        <meta name="twitter:description" content="John Shearin">
    {% endblock %}

    
    <title>
        {% block title%}JohnShearin.com{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
        type='text/css'>
    <link
        href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-X7NQ5H8CJL"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-X7NQ5H8CJL');
    </script>

</head>

<body>
    
    <!-- Navigation -->
    {% include 'partials/navbar.html'%}

    <!-- Page Header -->

    <!-- Insert Content -->
    {% block content %}{% endblock %}


    <!-- Footer -->
    <div align="center">
        <p class="copyright text-muted" style="font-size: .8rem; text-align: center">Copyright&copy; John Shearin 2021</p>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
    <!-- Tooltip jquery-->
    <script>$("[data-toggle=tooltip").tooltip();</script>

</body>

</html>

templates/partials/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/john-shearin/" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/jshearin01/" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
    <a class="navbar-brand" href="{% url 'home:home_base' %}">John Shearin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:home_page' %}">
              Home
          </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:about' %}">
                About
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home:resume' %}">
                Resume
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:all' %}">
                Blog
            </a>
        </li>
        {% if user.is_superuser %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'notes:all' %}">
                  Notes
              </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

templates/partials/pager.html
<!-- Pager -->
<div class="clearfix">
    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
</div>